figure(), hold on
plot(nodeArch.nodesLoc(:, 1), nodeArch.nodesLoc(:, 2),...
    '.','MarkerSize',10,'Color',[1 0 0]);
plot(netArch.Sink.x, netArch.Sink.y,'*', ...
    'MarkerSize',20,'Color',[0 1 0]);
